---
title: "Prueba de Hipótesis"
author: "Fernando A Barrios"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="80")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=80)
```

La prueba de hipótesis es una ayuda al investigador para alcanzar una conclusión relacionada a una población basada en una muestra tomada de dicha población. 

**Definición** Una hipótesis puede definirse como una declaración a cerca de una o más poblaciones.  
Clases de hipótesis, se puede decir que existen dos clases de hipótesis, las hipótesis de investigación y las hipótesis estadísticas.  

*Las hipótesis de investigación es una suposición qeu motiva la investigación.*  

Generalmente las hipótesis de invesotgación en su proceso experimental y de análisis de los datos relacionados con la parte experimental dan lugar a una (o varias) hipótesis estadísticas, que son necesarias para desarrollar la estimación de parámetros relacionados con las poblaciones estudiadas.  
*Las hipótesis estadísticas son hipótesis que están expresadas de tal forma que pueden ser evaluadas por medio de técnicas estádisticas adecuadas.*  

**Pasos para la Prueba de Hipótesis**, por motivos de conveniencia la prueba de hipótesis será presentada en un procedimineto de diez pasos.  
1. **Datos**. El tipo de datos es importante que se conozca para poder determinar que tipo de pruebas se pueden usar.  
2. **Supuestos**. Como ya se vio en el tema pasado de Estimación, dependiendo de la suposiciones que se hacen es necesario usar diferentes métodos de estimación, como lo son las distribuciones probabilísticas de los datos que ese están analizando, entre otros.  
3. **Hipótesis**. Hay dos hipótesis estadísticas involucradas con la prueba de hipótesis, y las dos deben de estar expresadas de forma explícita. La *hipótesis nula*, la hipótesis que se va a probar, designada por el símbolo $H_0$. Generalmente la hipótesis nula es aquella que se establece para ser desechada. La hipótesis nula es la que se rechaza o acepta. Si la hipótesis nula no se rechaza, se puede decir que los datos en los que la prueba está basada no dan suficiente evidencia para rechazarla. Y la segunda hipótesis es la *hipótesis alternativa* que es la declaración que se considerará como verdadera si se rechaza la hipótesis nula.  Por lo general la hipótesis alternativa y la hipótesis e investigación son la misma. Se describe con el símbolo $H_A$.  
4. **Estadística de prueba** La prueba estadística es la estadística que se puede correr con los datos de la muestra.  La prueba estadística es un método de prueba para tomar una decisión. La formula general para una prueba de hipótesis:  

$$ \verb+estadística de prueba+ = \frac{\verb+estadística relevante - parámetro hipótetisado+}{\verb+error estándar de la estadística relvante+} $$
como ejemplo  
$$ z = \frac{\bar{x} - \mu_0}{\sigma/\sqrt{n}} $$

5. **Distribución de la estadística de prueba** el punto clave de la estadística de prueba es la distribución de la estadística.  
6. **Regla de decisión** la región de rechazo o aceptación se determinan a partir de los valores críticos de la estadística de prueba.  Se rechaza la hipótesis nula si un valor de la prueba entra al rango de los valores de rechazo. Los valores del rango de rechazo se estiman con base en el **nivel de significancia** que se decidió usar en la prueba estadística. Se usa la definición para el nivel de significancia $\alpha$ como una probabilidad, de hecho es la probabilidad de rechazar la verdadera hipótesis nula.  
7. **Estimación de la estadística de prueba**, a partir de los datos de muestreo que se tienen se estima la estadística de prueba.  
8. **Decisión estadística**, esta decisión consiste en rechazar o aceprar la hipótesis nula.  
9. **Conclusión** Si $H_0$ se rechaza, se concluye que $H_A$ es verdadera, y si $H_0$ no se rechaza, se concluye que $H_0$ puede ser verdadera.
10. **valor $p$** el valor $p$ es el número (probabilidad) que nos indica que tan poco probables son los valores de nuestra muestra, dada la hipótesis nula.  



