---
title: "Pro_02"
author: "F.A. Barrios"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Proyecto final 1  
## Órtesis y Prótesis ENES Juriquilla.  
## F.A. Barrios  
## Uso de archivos de datos grandes BABY WGTS, capítulo 6  

1. Usando el archivo de los pesos de 1200 bebés nacidos en un hospital comunitario (LDS_C06_BABYWGTS.csv). Extraiga una muestra aleatoria simple de 20 sujetos de esta población construya un intervalo de confianza al 95 por ciento de confianza para el promedio de peso al nacer de esta población. Y además estime el intervalo de confianza para la varinaza del peso al nacer con una confianza del 95 por ciento. Use la función presentada en clase.   
2. Usando estos datos extraiga una muestra aleatoria de 35 sujetos y estime los mismos intervalos de convianza, usando esta muestra. Compare los resultados para las dos muestras y explique sus resultados. Use la función presentada en clase para estimar el intervalo de la varianza y promedio.  
3. Construya histogramas de las dos muestras y gráficas de caja.  En particular use información en la red para hacer una gráfica de violín de las muestras. De estás gráficas que se puede concluir?  
4. Para la muestra de 35 sujetos estime el intervalo de confianza al 99 por ciento, para el promedio y la varianza de peso al nacer de la población. Y calcule en promedio y varianza poblacional.  
5. Use la función `t.test()` para estimar los mismos parámetros de los puntos 1 y 2.  
