---
title: "Distribucion de Muestreo"
author: "F. A. Barrios<br>ENES Juriquilla, UNAM<br>"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```
# Distribucion de Muestras  
La distribución de todos los valores posibles que puede tomar una "estadística", construidos a partir de muestras del mismo tamaño de nuestra extraídas al azar de la misma población, es llamado la distribución de muestreo de esa "estadística".  

## Construcción de una distibución de muestras  
Una distribución de muestreo se puede construir empiricamente a partir de un muestreo discreto, de una población finita, de la siguiente forma  
1. De una población finita de tamaño $N$, se extraen todas las muestras posibles de tamaño $n$.  
2. La estadística de interés se estima en cada una de estas muestras.
3. En una lista se compilan todos los valores de la estadística obtenidos y todas las frecuencias de los valores obtenidos  

##Teoría del Muestreo  
**Definición** Se dice que las variables aleatorias $X_1, X_2, \dots, X_n$ cuya función de densidad de probabilidad conjunta es $f(x_1, x_2, \dots, x_n))$ y cuya funciones particulares de densidad son $f_1(x_1), f_2(x_2), \dots, f_n(x_n)$ son *independientes* siempre y cuando 
$$ f(x_1, x_2, \cdots, x_n) = f_1(x_1)f_2(x_2)\cdots f_n(x_n)$$

## Características de una distribución de muestras  
Por lo general se está interesado en estimar tres parámetros de una distribución de muestras: su *promedio*, su *varianza*, y su *forma funcional*.  Representemos por $f(x)$ la funcion de densidad de la variable aleatoria continua $X$ y por $n$ el tamaño de la puestra que se toma.Los valores muestrales que se resultantes se designan mediante los símbolos $x'_1, x'_2, \dots, x'_n$, Si se extrajera una segunda muestra de tamaño $n$ entonces a los valores muestrales resultantes se le designa por $x''_1, x''_2, \dots, x''_n$ y de igual forma para las restantes muestras. Estos valores los podemos representar en una tabla por conveniencia
$$\begin{array}{cccc}
  x'_1 & x'_2 & \dots & x'_n \\
  x''_1  & x''_2 & \dots & x''_n \\
  x'''_1 & x'''_2 & \dots & x'''_n \\
  \vdots & \vdots & \vdots & \vdots \\
  \bar{x}_1 & \bar{x}_2 & \cdots & \bar{x}_n \\
\end{array} $$

## La distribución de muestras del promedio: promedio  

El promedio de muestras es  
$$\mu_\bar{x} = \frac{\sum{\bar{x_i}}}{N^n}$$
Las propiedades de de la distribución del promedio de muestras de una distribución normal, supongamos que X (la población de dónde se hace el muestreo) tiene una distribución normal con media $\mu$ y varianza $\sigma^2/n$. Consideremos una muestra aleatoria de tamaño $n$ de esta población normal, la media de dicha muestra,
$$ \bar{X}=\frac{1}{n}(X_1 + \dots +X_n) $$

será una variable aleatoria por que las $X_1, X_2, \dots,X_n$ correspondientes a las $n$ pruebas de la nuestra son variables aleatorias.  Y se sigue que: Si $X$ tiene una distribución normal con media $\mu$ y varianza $\sigma^2$ y se toma una muestra aleatoria de tamaño $n$, la media muestral $\bar{X}$ tendrá una distribución normal con media $\mu$ y varianza $\sigma^2/n$
Es decir
$$ \sigma_{\bar{X}}^2 = \frac{1}{n^2}\sum_{i=1}^{n}\sigma^2 = \frac{\sigma^2}{n} $$

Puesto que muchas variables experimentales pueden tener distribuciones que no son normales, es importante saber si las propiedades del promedio de las medias de muestreo (y sus propiedades de la varianza) pueden ser descritas. Se puede destacar que sin importar cuál sea el tipo de distribución que tenga pa población $X$, siempre que existan su media y su varianza, la distribución de $\bar{X}$ tenderá a la distribución normal cuando $n \rightarrow \infty$ , que es lo que se conoce como el *Teorema Central del Límite*  
**Teorema central del límite:** Si $X$ es una variable aleatoria con media $\mu$ y varianza $\sigma^2$, la variable aleatoria $Z=(\bar{X} - \mu)\sqrt{n}/\sigma$ tiene una distribución que se aproxima a la distribución normal normalizada (tipificada) cuando $n \rightarrow \infty$.  


##  La distribución de muestras del promedio: varianza  

La varianza del promedio de muestra  
$$ {\sigma_{\bar{x}}^2} = \frac{\sum{(\bar{x}_i}-\mu_{\bar x})^2}{N^n} = \frac{\sigma^2}{n}$$
La raíz cuadrada de la varinaza de la distribución de muestras, $\sqrt{\sigma_{\bar{x}}^2} = \sigma_{\bar{x}}/\sqrt{n}$ es llamada el error estándar del promedio o simplemente el *error estándar*.  

*Cuando el muestreo se hace sin remplazo* de una población finita, la distribución de $\bar{X}$ tendrá una promedio $\mu$ y varianza  
$$ \sigma_{\bar{X}}^2 = \frac{\sigma^2}{n} \frac{N - n}{N -1} $$
(con corrección para una población finita)  

*En resumen* LA distribución de muestreo para $\bar{X}$ es:  
1. El muestreo de una población distribuida normalmente con varianza de la población conocida:
a) $\mu_{\bar{X}} = \mu$  
b) $\sigma_{\bar{X}} = \sigma/\sqrt{n}$  
c) La distribución de $\bar{X}$ es normal  

2. El muestreo es de una poblaión con una distribución no-normal con varinza conocida:  
a) $\mu_{\bar{X}} = \mu$  
b) $\sigma_{\bar{X}} = \sigma/\sqrt{n}$ cuando $n/N \leq .05$  
   $\sigma_{\bar{X}} = \frac{\sigma}{\sqrt{n}} \sqrt{\frac{N - n}{N -1}}$, de otra forma.
c) La distribución de $\bar{X}$ es aproximadamente normal.  












